### ISSUE TITLE
distant.json文件是如何获得的？

### ISSUE THREAD

**Issue by zjucheri** [thunlp/Neural-Snowball#1]
paper里表示无标注数据来自维基百科，一共899,996个instance，464,218个实体对。对应data文件下的distant.json，数据的关系类别标注一共744种，请问这里丰富的关系种类标注是如何获得的？是依据各种关系instance，然后远程监督的吗？

**Comment by gaotianyu1350** [comment]
Hi，

是利用wikipedia dump和wikidata远程监督得到的。

**Comment by zjp9574** [comment]
Hi，
利用wikipedia dump和wikidata远程监督得到的，这个代码和数据能否共享一下呢，🙏🙏🙏🙏🙏。
