### ISSUE TITLE
关于“Neural Snowball for Few-Shot Relation Learning”遇到问题

### ISSUE THREAD

**Issue by tangdouer** [thunlp/Neural-Snowball#2]
您好：
     看您的文章“Neural Snowball for Few-Shot Relation Learning”过程中遇到两个问题，想向您请教。
     1. 这篇文章中候选集2和最后关系分类所用的分类器都是图中的C吗？
     2. 关系分类器C是提前利用大规模有监督数据训练好的二分类器吗？然后再利用候选集合1得到的数据对分类器进行微调，然后用于从无监督数据中得到第二阶段的候选集2吗。
谢谢您！

**Comment by gaotianyu1350** [comment]
1和2的理解都是对的～
