### ISSUE TITLE
Some question about the result

### ISSUE THREAD

**Issue by Bosen-Zhang** [thunlp/Neural-Snowball#3]
Thank you very much for your work.
I ran your code according to your instructions, and the results are as follows:
0.4107656741158835 0.3738097444120933 0.7134000000000019 
0.43545527500531944 0.35403868367640734 0.7528200000000013
It seems that the results in Table 1 in your paper are not reached. Does the data in the paper refer to the test set, or do some settings need to be modified?

**Comment by gaotianyu1350** [comment]
Hi~ For your question,

1. The reported result is for the test set.
2. You can try to run the evaluation for a longer time to get a more stable result.

**Comment by Bosen-Zhang** [comment]
I don't seem to see the early stopping mechanism in the code. Is it possible that too many iters have caused the overfitting problem?

**Comment by gaotianyu1350** [comment]
That's not a problem. For each episode we use newly initialized parameters for the classifier. Note that during evaluation the encoder parameters are not updated.

**Comment by Bosen-Zhang** [comment]
If I set batch_size to 1024, do other values need to be modified?
