### ISSUE TITLE
是否会出现过拟合问题？

### ISSUE THREAD

**Issue by Bosen-Zhang** [thunlp/Neural-Snowball#4]
我似乎没有在代码内部发现早停机制？eval-iter默认设置为1000是否会出现过拟合问题？

**Comment by Bosen-Zhang** [comment]
除此之外因为本身gpu的限制，如果不设置batch_size无法运行代码，我将batch_size设置为1024，eval_iter是否需要修改？

**Comment by gaotianyu1350** [comment]
如#3所述，不会有过拟合问题，最后evaluation的iter和结果好坏没关系，只是测的越多结果越稳定，所以可以根据需要随意调整
