### ISSUE TITLE
请教关于迭代次数的问题

### ISSUE THREAD

**Issue by tangdouer** [thunlp/Neural-Snowball#5]
您好，遇到以下几个问题需要向您请教：
假设每个类别选取5个种子，每一次通过一个种子去从无监督数据中挖掘有效信息，请问这一个种子的迭代停止条件是什么呢，怎么判断到达了峰值呢？另外第2个种子从什么时候开始去从无监督数据中挖掘有效信息呢?

**Comment by gaotianyu1350** [comment]
每一次都是从所有种子挖掘信息的，迭代停止看轮数。详情可以参考论文。
