### ISSUE TITLE
关于使用15个种子时的结果问题

### ISSUE THREAD

**Issue by lorylee** [thunlp/Neural-Snowball#6]
您好，我跑了几遍您的代码，但是在使用15个种子时效果和您论文中的相差很多，不知道是什么原因，望您可以解答一下，十分感谢！！

当eval_iter设置到3000时结果  f1:48.56  prec:42.70  recall:60.76

**Comment by gaotianyu1350** [comment]
你用的是什么encoder呢？

**Comment by lorylee** [comment]
CNN

**Comment by gaotianyu1350** [comment]
能否提供下完整的运行环境和script？以及在seed=5 seed=10时的结果

**Comment by lorylee** [comment]
运行环境：python 3.7  pytorch 1.5.1
seed =5结果：  eval_iter=1000     f1: 41.18     prec: 45.17   recall: 42.78
                                                       f1: 43.09     prec: 47.65   recall: 44.56
seed =10结果：eval_iter=1000     f1: 49.93     prec: 46.81   recall: 57.14
                                                       f1: 49.30     prec: 47.35   recall: 55.43
seed =15结果：eval_iter=1000     f1: 48.44     prec: 42.41   recall: 61.10
seed =15结果：eval_iter=1500     f1: 48.76     prec: 43.03   recall: 60.96
seed =15结果：eval_iter=3000     f1:48.56      prec:42.70     recall:60.76

按照您的readme: 先预训练cnn encoder  预训练 cnn siamese

**Comment by gaotianyu1350** [comment]
十分抱歉，确实是有一个地方公开仓库里的版本参数设置错了，目前已修正并push。感谢你的反馈！

ps. 因为test集是FewRel benchmark的一部分没有公开，和在val集上的结果绝对数值上略有差别，但趋势是一致的。
