### ISSUE TITLE
How can i  find the entry to the classifier training code

### ISSUE THREAD

**Issue by ybsun0215** [thunlp/Neural-Snowball#8]
Hi, Brother Gao, I am a student in a domestic school. Our teacher said that your paper was very good and asked me to reproduce your paper, but I couldn't find the code for the classifier to start training, could you help me?

**Comment by gaotianyu1350** [comment]
Hi,

The `train_xxx_encoder` files are for training the initial encoder and classifiers.

**Comment by ybsun0215** [comment]
I carefully debug the code, I think the relationship classifier is started to be trained in the snowball, DO you agree?
In addition, I would like to know why there are masks in cnn_snowball? Because I see only Word and POS for Encoder input. 
Mask  use for PCNN ？ but I don't see PCNN used.

**Comment by gaotianyu1350** [comment]
The snowball part is all in the test_* files.

**Comment by ybsun0215** [comment]
Thank you for your answer and hope you enjoy your life abroad!
